# Generated by Django 5.0 on 2023-12-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packinglist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='assigned_to',
        ),
    ]
